### ISSUE TITLE
When you upgrade your codes to 1.0.0 version?

### ISSUE THREAD

**Issue by MehdiDehghani** [jchadwick/UpAndRunningWithAspNet5#3]
Hello,
I saw your videos, good one, thanks.

I wondering when you upgrade your codes to 1.0.0 version, also your course (as you told in last video, you will re-record whole course after version 1 released)?

Be safe.

**Comment by jchadwick** [comment]
Hey Mehdi,

Thanks for the comment.  Yes, I have already begun the planning to re-record the whole course once RTM is released.  I should be coming out about mid-November.
